apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpd-service
  labels:
    app: cpd-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpd-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cpd-service
    spec:
      containers:
      - name: cpd-service
        image: springboot-postgres-k8s:10
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres-conf
                key: name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD


            
---
apiVersion: v1
kind: Service
metadata:
  name: cpd-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cpd-service

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  # namespace: default
  labels:
    app: lookalike-service
    deploymentName: lookalike-service
spec:
  scaleTargetRef:
    name: lookalike-service
  pollingInterval: 10
  cooldownPeriod:  15
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"